basePath: /api/v1
consumes:
- application/json
definitions:
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  models.AggregateData:
    properties:
      count: {}
    type: object
  models.Color:
    properties:
      code:
        type: string
      created_at:
        type: string
      deleted_at:
        $ref: '#/definitions/gorm.DeletedAt'
      hex:
        type: string
      id:
        type: integer
      name:
        type: string
      updated_at:
        type: string
    type: object
  models.DataAuthResponse:
    properties:
      access_token:
        type: string
      expires:
        type: integer
    type: object
  models.Fabric:
    properties:
      code:
        type: string
      color:
        $ref: '#/definitions/models.Color'
      color_id:
        type: integer
      cost:
        type: number
      created_at:
        type: string
      deleted_at:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      key:
        type: string
      name:
        type: string
    type: object
  models.Image:
    properties:
      id:
        type: string
      location:
        type: string
    type: object
  models.LoginUser:
    properties:
      password:
        maxLength: 20
        minLength: 8
        type: string
      username:
        maxLength: 30
        type: string
    required:
    - password
    - username
    type: object
  models.Reference:
    properties:
      back:
        type: string
      back_image:
        $ref: '#/definitions/models.Image'
      create_by:
        type: string
      created_at:
        type: string
      deleted_at:
        $ref: '#/definitions/gorm.DeletedAt'
      front:
        type: string
      front_image:
        $ref: '#/definitions/models.Image'
      id:
        type: integer
      key:
        type: string
      reference:
        type: string
      user:
        $ref: '#/definitions/models.User'
    type: object
  models.Resource:
    properties:
      code:
        type: string
      color:
        $ref: '#/definitions/models.Color'
      color_id:
        type: integer
      cost:
        type: number
      created_at:
        type: string
      deleted_at:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      key:
        type: string
      name:
        type: string
    type: object
  models.Supplier:
    properties:
      created_at:
        type: string
      deleted_at:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      name:
        type: string
      nit:
        type: string
      updated_at:
        type: string
    type: object
  models.User:
    properties:
      created_at:
        type: string
      deleted_at:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: string
      name:
        type: string
      password:
        type: string
      role:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
  title: Vytex API
  version: "0.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Given a correct user name and password get access
      parameters:
      - description: User's credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.LoginUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.DataAuthResponse'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: Login
      tags:
      - Auth
  /auth/logout:
    post:
      consumes:
      - application/json
      description: Remove the refresh token from the database and delete the cookie
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: Logout
      tags:
      - Auth
  /auth/refresh:
    post:
      description: Given a correct refresh cookie get access
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.DataAuthResponse'
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: Refresh
      tags:
      - Auth
  /colors:
    get:
      description: Get all the colors, limit for query o default limit
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Color'
            type: array
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get colors from db
      tags:
      - Colors
    post:
      description: Create a new color
      parameters:
      - description: Color create values
        in: body
        name: models.ColorCreateBody
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Color'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Create color
      tags:
      - Colors
  /colors/aggregate:
    get:
      description: Get result of aggregate function from colors
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.AggregateData'
            type: array
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get aggregate from colors
      tags:
      - Colors
  /fabrics:
    get:
      description: Get all the fabrics, limit for query o default limit
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Fabric'
            type: array
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get fabrics from db
      tags:
      - Fabrics
  /fabrics/aggregate:
    get:
      description: Get aggregate from fabrics
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.AggregateData'
            type: array
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get aggregate from fabrics
      tags:
      - Fabrics
  /images:
    post:
      description: Create a new image
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            items:
              $ref: '#/definitions/models.Image'
            type: array
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Create image
      tags:
      - Files
  /reference:
    post:
      description: Create a new reference
      parameters:
      - description: Reference create values
        in: body
        name: models.ReferenceCreateBody
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Reference'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Create reference
      tags:
      - References
  /resources:
    get:
      description: Get all the resources, limit for query o default limit
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Resource'
            type: array
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get resources from db
      tags:
      - Resources
  /resources/aggregate:
    get:
      description: Get result of aggregate function from resources
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.AggregateData'
            type: array
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get aggregate from resources
      tags:
      - Resources
  /suppliers:
    get:
      description: Get all the suppliers, limit for query o default limit
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Supplier'
            type: array
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get suppliers from db
      tags:
      - Suppliers
  /suppliers/aggregate:
    get:
      description: Get result of aggregate function from suppliers
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.AggregateData'
            type: array
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get aggregate from suppliers
      tags:
      - Suppliers
  /users:
    get:
      description: Get all the users, limit for query o default limit
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get users from db
      tags:
      - Users
    post:
      description: Create a new user
      parameters:
      - description: User create values
        in: body
        name: models.UserCreateBody
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Create user
      tags:
      - Users
  /users/{userId}:
    post:
      description: Updates the fields from user
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: string
      - description: User update values
        in: body
        name: models.UpdateUserBody
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Update use
      tags:
      - Users
  /users/aggregate:
    get:
      description: Get result of aggregate function from users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.AggregateData'
            type: array
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get aggregate from users
      tags:
      - Users
  /users/me:
    get:
      description: Get the user who do the request with access token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get the curren user loggged
      tags:
      - Users
  /users/userId:
    get:
      description: Get an user by its ID
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get a given user
      tags:
      - Users
swagger: "2.0"
