services:

  api-test:
    container_name: api-test
    build:
      dockerfile: dockerfile.test.api
      context: ./.docker/
    volumes:
      - ./api/:/app
    ports:
    - 8080:8080
    networks:
    - app-net
    - api-net
    depends_on:
      db-test:
        condition: service_healthy
    
  app-test:
    container_name: app-test
    build:
      dockerfile: dockerfile.test.app
      context: ./.docker/
    command: sh -c 'cd app && npm run dev'
    volumes:
        - ./:/app
    ports:
    - 4040:4040
    networks:
    - app-net
    depends_on:
      api-test:
        condition: service_started
          
  db-test:
    image: postgres:16
    container_name: db-test
    environment:
      - POSTGRES_USER=vytex_test
      - POSTGRES_PASSWORD=vytex_test
      - POSTGRES_DB=vytex_test
    volumes:
      - db-test-vytex:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - api-net
    attach: false
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 3s
      timeout: 3s
      retries: 5

  pg-admin:
    image: dpage/pgadmin4:8.5
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - "5050:80"
    volumes:
      - pgadmin-vytex:/var/lib/pgadmin
    restart: unless-stopped
    networks:
      - api-net
    attach: false
    depends_on:
      db-test:
        condition: service_healthy

networks:
  app-net:
  api-net:

volumes:
  pgadmin-vytex:
  db-test-vytex:

# to run: docker compose -f docker-compose-test.yaml up
# remove logs from other services
#  logging:
#     driver: none
#    attach: false

