export const POLICIES = [
	'ReadUsers',
	'CreateUsers',
	'UpdateUsers',
	'ReadColors',
	'CreateColors',
	'UpdateColors',
	'ReadCustoms',
	'CreateCustoms',
	'UpdateCustoms',
	'ReadFabrics',
	'CreateFabrics',
	'UpdateFabrics',
	'ReadOrders',
	'CreateOrders',
	'UpdateOrders',
	'ReadReferences',
	'CreateReferences',
	'UpdateReferences',
	'UpdateTimesReferences',
	'ReadResources',
	'CreateResources',
	'UpdateResources',
	'ReadSuppliers',
	'CreateSuppliers',
	'UpdateSuppliers',
] as const;

export type Policy = (typeof POLICIES)[number];
