// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/knovalab-systems/vytex/app/v1/models"
)

func newResource(db *gorm.DB, opts ...gen.DOOption) resource {
	_resource := resource{}

	_resource.resourceDo.UseDB(db, opts...)
	_resource.resourceDo.UseModel(&models.Resource{})

	tableName := _resource.resourceDo.TableName()
	_resource.ALL = field.NewAsterisk(tableName)
	_resource.ID = field.NewUint(tableName, "id")
	_resource.Key = field.NewString(tableName, "key")
	_resource.Name = field.NewString(tableName, "name")
	_resource.Cost = field.NewFloat64(tableName, "cost")
	_resource.Code = field.NewString(tableName, "code")
	_resource.ColorID = field.NewUint(tableName, "color_id")
	_resource.SupplierID = field.NewUint(tableName, "supplier_id")
	_resource.CreatedAt = field.NewTime(tableName, "created_at")
	_resource.DeletedAt = field.NewField(tableName, "deleted_at")
	_resource.Color = resourceBelongsToColor{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Color", "models.Color"),
	}

	_resource.Supplier = resourceBelongsToSupplier{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Supplier", "models.Supplier"),
	}

	_resource.fillFieldMap()

	return _resource
}

type resource struct {
	resourceDo

	ALL        field.Asterisk
	ID         field.Uint
	Key        field.String
	Name       field.String
	Cost       field.Float64
	Code       field.String
	ColorID    field.Uint
	SupplierID field.Uint
	CreatedAt  field.Time
	DeletedAt  field.Field
	Color      resourceBelongsToColor

	Supplier resourceBelongsToSupplier

	fieldMap map[string]field.Expr
}

func (r resource) Table(newTableName string) *resource {
	r.resourceDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r resource) As(alias string) *resource {
	r.resourceDo.DO = *(r.resourceDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *resource) updateTableName(table string) *resource {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewUint(table, "id")
	r.Key = field.NewString(table, "key")
	r.Name = field.NewString(table, "name")
	r.Cost = field.NewFloat64(table, "cost")
	r.Code = field.NewString(table, "code")
	r.ColorID = field.NewUint(table, "color_id")
	r.SupplierID = field.NewUint(table, "supplier_id")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.DeletedAt = field.NewField(table, "deleted_at")

	r.fillFieldMap()

	return r
}

func (r *resource) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *resource) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 11)
	r.fieldMap["id"] = r.ID
	r.fieldMap["key"] = r.Key
	r.fieldMap["name"] = r.Name
	r.fieldMap["cost"] = r.Cost
	r.fieldMap["code"] = r.Code
	r.fieldMap["color_id"] = r.ColorID
	r.fieldMap["supplier_id"] = r.SupplierID
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["deleted_at"] = r.DeletedAt

}

func (r resource) clone(db *gorm.DB) resource {
	r.resourceDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r resource) replaceDB(db *gorm.DB) resource {
	r.resourceDo.ReplaceDB(db)
	return r
}

type resourceBelongsToColor struct {
	db *gorm.DB

	field.RelationField
}

func (a resourceBelongsToColor) Where(conds ...field.Expr) *resourceBelongsToColor {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a resourceBelongsToColor) WithContext(ctx context.Context) *resourceBelongsToColor {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a resourceBelongsToColor) Session(session *gorm.Session) *resourceBelongsToColor {
	a.db = a.db.Session(session)
	return &a
}

func (a resourceBelongsToColor) Model(m *models.Resource) *resourceBelongsToColorTx {
	return &resourceBelongsToColorTx{a.db.Model(m).Association(a.Name())}
}

type resourceBelongsToColorTx struct{ tx *gorm.Association }

func (a resourceBelongsToColorTx) Find() (result *models.Color, err error) {
	return result, a.tx.Find(&result)
}

func (a resourceBelongsToColorTx) Append(values ...*models.Color) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a resourceBelongsToColorTx) Replace(values ...*models.Color) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a resourceBelongsToColorTx) Delete(values ...*models.Color) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a resourceBelongsToColorTx) Clear() error {
	return a.tx.Clear()
}

func (a resourceBelongsToColorTx) Count() int64 {
	return a.tx.Count()
}

type resourceBelongsToSupplier struct {
	db *gorm.DB

	field.RelationField
}

func (a resourceBelongsToSupplier) Where(conds ...field.Expr) *resourceBelongsToSupplier {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a resourceBelongsToSupplier) WithContext(ctx context.Context) *resourceBelongsToSupplier {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a resourceBelongsToSupplier) Session(session *gorm.Session) *resourceBelongsToSupplier {
	a.db = a.db.Session(session)
	return &a
}

func (a resourceBelongsToSupplier) Model(m *models.Resource) *resourceBelongsToSupplierTx {
	return &resourceBelongsToSupplierTx{a.db.Model(m).Association(a.Name())}
}

type resourceBelongsToSupplierTx struct{ tx *gorm.Association }

func (a resourceBelongsToSupplierTx) Find() (result *models.Supplier, err error) {
	return result, a.tx.Find(&result)
}

func (a resourceBelongsToSupplierTx) Append(values ...*models.Supplier) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a resourceBelongsToSupplierTx) Replace(values ...*models.Supplier) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a resourceBelongsToSupplierTx) Delete(values ...*models.Supplier) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a resourceBelongsToSupplierTx) Clear() error {
	return a.tx.Clear()
}

func (a resourceBelongsToSupplierTx) Count() int64 {
	return a.tx.Count()
}

type resourceDo struct{ gen.DO }

type IResourceDo interface {
	gen.SubQuery
	Debug() IResourceDo
	WithContext(ctx context.Context) IResourceDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IResourceDo
	WriteDB() IResourceDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IResourceDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IResourceDo
	Not(conds ...gen.Condition) IResourceDo
	Or(conds ...gen.Condition) IResourceDo
	Select(conds ...field.Expr) IResourceDo
	Where(conds ...gen.Condition) IResourceDo
	Order(conds ...field.Expr) IResourceDo
	Distinct(cols ...field.Expr) IResourceDo
	Omit(cols ...field.Expr) IResourceDo
	Join(table schema.Tabler, on ...field.Expr) IResourceDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IResourceDo
	RightJoin(table schema.Tabler, on ...field.Expr) IResourceDo
	Group(cols ...field.Expr) IResourceDo
	Having(conds ...gen.Condition) IResourceDo
	Limit(limit int) IResourceDo
	Offset(offset int) IResourceDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IResourceDo
	Unscoped() IResourceDo
	Create(values ...*models.Resource) error
	CreateInBatches(values []*models.Resource, batchSize int) error
	Save(values ...*models.Resource) error
	First() (*models.Resource, error)
	Take() (*models.Resource, error)
	Last() (*models.Resource, error)
	Find() ([]*models.Resource, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Resource, err error)
	FindInBatches(result *[]*models.Resource, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Resource) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IResourceDo
	Assign(attrs ...field.AssignExpr) IResourceDo
	Joins(fields ...field.RelationField) IResourceDo
	Preload(fields ...field.RelationField) IResourceDo
	FirstOrInit() (*models.Resource, error)
	FirstOrCreate() (*models.Resource, error)
	FindByPage(offset int, limit int) (result []*models.Resource, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IResourceDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r resourceDo) Debug() IResourceDo {
	return r.withDO(r.DO.Debug())
}

func (r resourceDo) WithContext(ctx context.Context) IResourceDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r resourceDo) ReadDB() IResourceDo {
	return r.Clauses(dbresolver.Read)
}

func (r resourceDo) WriteDB() IResourceDo {
	return r.Clauses(dbresolver.Write)
}

func (r resourceDo) Session(config *gorm.Session) IResourceDo {
	return r.withDO(r.DO.Session(config))
}

func (r resourceDo) Clauses(conds ...clause.Expression) IResourceDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r resourceDo) Returning(value interface{}, columns ...string) IResourceDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r resourceDo) Not(conds ...gen.Condition) IResourceDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r resourceDo) Or(conds ...gen.Condition) IResourceDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r resourceDo) Select(conds ...field.Expr) IResourceDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r resourceDo) Where(conds ...gen.Condition) IResourceDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r resourceDo) Order(conds ...field.Expr) IResourceDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r resourceDo) Distinct(cols ...field.Expr) IResourceDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r resourceDo) Omit(cols ...field.Expr) IResourceDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r resourceDo) Join(table schema.Tabler, on ...field.Expr) IResourceDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r resourceDo) LeftJoin(table schema.Tabler, on ...field.Expr) IResourceDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r resourceDo) RightJoin(table schema.Tabler, on ...field.Expr) IResourceDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r resourceDo) Group(cols ...field.Expr) IResourceDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r resourceDo) Having(conds ...gen.Condition) IResourceDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r resourceDo) Limit(limit int) IResourceDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r resourceDo) Offset(offset int) IResourceDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r resourceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IResourceDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r resourceDo) Unscoped() IResourceDo {
	return r.withDO(r.DO.Unscoped())
}

func (r resourceDo) Create(values ...*models.Resource) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r resourceDo) CreateInBatches(values []*models.Resource, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r resourceDo) Save(values ...*models.Resource) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r resourceDo) First() (*models.Resource, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Resource), nil
	}
}

func (r resourceDo) Take() (*models.Resource, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Resource), nil
	}
}

func (r resourceDo) Last() (*models.Resource, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Resource), nil
	}
}

func (r resourceDo) Find() ([]*models.Resource, error) {
	result, err := r.DO.Find()
	return result.([]*models.Resource), err
}

func (r resourceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Resource, err error) {
	buf := make([]*models.Resource, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r resourceDo) FindInBatches(result *[]*models.Resource, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r resourceDo) Attrs(attrs ...field.AssignExpr) IResourceDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r resourceDo) Assign(attrs ...field.AssignExpr) IResourceDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r resourceDo) Joins(fields ...field.RelationField) IResourceDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r resourceDo) Preload(fields ...field.RelationField) IResourceDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r resourceDo) FirstOrInit() (*models.Resource, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Resource), nil
	}
}

func (r resourceDo) FirstOrCreate() (*models.Resource, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Resource), nil
	}
}

func (r resourceDo) FindByPage(offset int, limit int) (result []*models.Resource, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r resourceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r resourceDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r resourceDo) Delete(models ...*models.Resource) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *resourceDo) withDO(do gen.Dao) *resourceDo {
	r.DO = *do.(*gen.DO)
	return r
}
